skgusskgusgg/1st_project

- src/main/java/org/team/join/MemberDTO.java
- src/main/java/org/team/join/MemberService.java
- src/main/java/org/team/join/MemberServiceImpl.java
- src/main/java/org/team/mapper/MemberMapper.java
- src/main/resources/org/team/mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- src/main/webapp/WEB-INF/views/join/join.jsp
- src/main/webapp/WEB-INF/views/join/openApiAddress.jsp
- 회원가입 페이지
- 전체유효성 검사 
- 주소api 기능 
풀 리퀘스트 요청 드립니다.
> 회원가입, 전체유효성, 주소api 기능 업데이트

- src/main/java/org/team/controller/JoinController.java
> joinController추가

- src/main/java/org/team/controller/MemberController.java
- src/main/java/org/team/mapper/MemberMapper.java
- src/main/java/org/team/member/MemberService.java
- src/main/java/org/team/member/MemberServiceImpl.java
- src/main/java/org/team/member/MemberVO.java
- src/main/resources/org/team/mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/views/includes/footer.jsp
- src/main/webapp/WEB-INF/views/includes/header.jsp
- src/main/webapp/WEB-INF/views/loginForm.jsp
- 로그인 유효성 구현 + 로그인 정보가 DB에 없으면 없다고 modal 안에서 나타나도록 구현
- 메인 화면에서 어떤 사용자로 로그인했는지 구현, 어떤 사용자로 로그인했냐에 따라 표시되는 메뉴 버튼 다르게 구현 -> 일반회원으로 로그인하면 (고객센터, 회원정보, 로그아웃)이 표시되고, 관리자로 로그인 하면 관리 메뉴들이 뜨게 구현함
- 로그아웃 구현 (session이 초기화되면서 메인화면으로 이동하게 구현)
> 로그인 기능 구현 (modal)

- src/main/java/org/team/controller/JoinController.java
- src/main/webapp/WEB-INF/spring/root-context.xml
- src/main/webapp/WEB-INF/views/join/join.jsp
- src/main/webapp/WEB-INF/views/join/openApiAddress.jsp
- join과 login의 form의 이름 수정 (둘다 frm이어서 join의 frm -> frm1으로), email과 password도 겹쳐서 login에서의 이름을 앞에 l 붙여서 해결
- javascript 중 phone이어야 하는게 '콜'로 바뀌어 있어서 변경
- 회원가입하고 난 후 바로 메인으로 가게 코드 수정
- rootcontext 경로 수정
> join login 오류 해결

- src/main/webapp/WEB-INF/views/product/productList.jsp
> productList css 수정

- src/main/java/org/team/controller/FAQController.java
- src/main/webapp/WEB-INF/views/includes/header.jsp
> 페이징 안되던 오류 수정

- src/main/webapp/WEB-INF/web.xml
- 회원가입 시, 한글깨짐 => 필터 추가[web.xml]
> - 회원가입 시, 한글깨짐 => 필터 추가

- src/main/webapp/WEB-INF/views/home.jsp
- src/main/webapp/WEB-INF/views/wishList/wish.jsp
- home.jsp에서 링크처리
- wishList 버튼 폰트 컬러 수정
> wishList Modify

- src/main/java/org/team/controller/AminHomeController.java
- src/main/java/org/team/controller/QnAController.java
- src/main/webapp/WEB-INF/views/admin/home.jsp
> admin/auth 브랜치 수정

- src/main/java/org/team/controller/FAQController.java
- src/main/java/org/team/controller/ProductDetailModalController.java
- src/main/java/org/team/controller/WishController.java
- src/main/java/org/team/mapper/ProductMapper.java
- src/main/java/org/team/service/ProductService.java
- src/main/java/org/team/service/ProductServiceImpl.java
- src/main/resources/org/team/mapper/ProductMapper.xml
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
- src/main/webapp/WEB-INF/views/product/productDetailModal.jsp
- src/main/webapp/WEB-INF/views/product/productList.jsp
- src/main/webapp/resources/js/addWish.js
- src/main/webapp/resources/js/wishList.js
- src/test/java/org/team/mapper/ProductMapperTests.java
- src/test/java/org/team/mapper/WishMapperTests.java
> - conflict 해결 detail

- src/main/webapp/WEB-INF/views/includes/footer.jsp
- src/main/webapp/WEB-INF/views/payment/payment.jsp
> payment jsp 수정

- src/main/java/org/team/controller/ReplyController.java
- src/main/resources/org/team/mapper/ReplyMapper.xml
- src/main/webapp/WEB-INF/views/admin/product/productDetail.jsp
- src/main/webapp/WEB-INF/views/cart/cartList.jsp
- src/main/webapp/WEB-INF/views/payment/payment.jsp
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
- src/main/webapp/resources/css/cart.css
- src/main/webapp/resources/js/cart.js
cart, payment, admin reply modify
> cart, payment, admin reply modify

- src/main/webapp/WEB-INF/views/payment/payment.jsp
> payment address modify

- src/main/java/org/team/admin/AdminPageDTO.java
- src/main/java/org/team/admin/AdminService.java
- src/main/java/org/team/admin/AdminServiceImpl.java
- src/main/java/org/team/controller/AdminDeliveryController.java
- src/main/java/org/team/controller/AdminManagementController.java
- src/main/java/org/team/controller/AdminOrderController.java
- src/main/java/org/team/delivery/deliveryDTO.java
- src/main/java/org/team/mapper/AdminMapper.java
- src/main/resources/org/team/mapper/AdminMapper.xml
- src/main/webapp/WEB-INF/views/admin/deliveryManagement.jsp
- src/main/webapp/WEB-INF/views/admin/memberManagement.jsp
- src/main/webapp/WEB-INF/views/admin/orderManagement.jsp
- 관리자모드  각각 회원, 오더, 딜리버리 페이지에 RUD 기능 추가 완료
> - 관리자모드  각각 회원, 오더, 딜리버리 페이지에 RUD 기능 추가 완료

- src/main/java/org/team/controller/paymentContorller.java
- src/main/webapp/WEB-INF/views/payment/payment.jsp
payment 1.0E7 over amount modify
> payment 1.0E7 over amount modify

- src/main/java/org/team/controller/paymentContorller.java
- src/main/java/org/team/mapper/PaymentMapper.java
- src/main/java/org/team/service/PaymentService.java
- src/main/java/org/team/service/PaymentServiceImpl.java
- src/main/resources/org/team/mapper/PaymentMapper.xml
- src/main/webapp/WEB-INF/views/payment/payment.jsp
Perform mVO update after payment
> Perform mVO update after payment

- src/main/java/org/team/controller/MyPageController.java
- src/main/java/org/team/mapper/OrderMapper.java
- src/main/java/org/team/mypage/orderCriteria.java
- src/main/java/org/team/mypage/orderService.java
- src/main/java/org/team/mypage/orderServiceImpl.java
- src/main/resources/org/team/mapper/OrderMapper.xml
- src/main/webapp/WEB-INF/views/mypage/myPage.jsp
> - myPage 수정 완료

- src/main/java/org/team/controller/MyPageController.java
- src/main/java/org/team/mapper/OrderMapper.java
- src/main/java/org/team/mypage/orderService.java
- src/main/java/org/team/mypage/orderServiceImpl.java
- src/main/resources/org/team/mapper/OrderMapper.xml
- src/main/webapp/WEB-INF/views/mypage/orderTracking.jsp
> - Mypage / Order Tracking

- src/main/java/org/team/mypage/orderWithProductDTO.java
- src/main/webapp/WEB-INF/views/admin/deliveryManagement.jsp
- src/main/webapp/WEB-INF/views/admin/orderManagement.jsp
- 오더+프로덕트DTO && 배송 0~2 => 1~3 변경
> - 오더+프로덕트DTO && 배송 0~2 => 1~3 변경

- src/main/java/org/team/controller/AdminOrderController.java
- src/main/webapp/WEB-INF/views/admin/deliveryManagement.jsp
-  delivery 관리자 페이지 배송번호 수정 => 1,2,3
> - -  delivery 관리자 페이지 배송번호 수정 => 1,2,3

- src/main/webapp/WEB-INF/views/product/productDetail.jsp
> product review 수정

- src/main/java/org/team/controller/ProductController.java
- src/main/resources/org/team/mapper/ProductMapper.xml
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
- 옵션에 컬러, 사이즈 재고가 있는 옵션만 들어가게 맞게 수정(controller, xml, jsp)
> product detail 페이지

- src/main/java/org/team/board/BoardVO.java
- src/main/java/org/team/controller/AdminBoardController.java
- src/main/java/org/team/controller/AdminFaqController.java
- src/main/java/org/team/controller/AdminProductController.java
- src/main/java/org/team/controller/BoardController.java
- src/main/java/org/team/controller/FaqController.java
- src/main/java/org/team/faq/FaqBoardVO.java
- src/main/java/org/team/faq/FaqReplyVO.java
- src/main/java/org/team/faq/FaqService.java
- src/main/java/org/team/faq/FaqServiceImpl.java
- src/main/java/org/team/mapper/FaqBoardMapper.java
- src/main/resources/org/team/mapper/BoardMapper.xml
- src/main/resources/org/team/mapper/FaqBoardMapper.xml
- src/main/webapp/WEB-INF/views/admin/board/boardDetail.jsp
- src/main/webapp/WEB-INF/views/admin/board/boardEdit.jsp
- src/main/webapp/WEB-INF/views/admin/board/boardList.jsp
- src/main/webapp/WEB-INF/views/admin/faq/faqDetail.jsp
- src/main/webapp/WEB-INF/views/admin/faq/faqEdit.jsp
- src/main/webapp/WEB-INF/views/admin/faq/faqList.jsp
- src/main/webapp/WEB-INF/views/admin/faq/writeFaq.jsp
- src/main/webapp/WEB-INF/views/board/boardDetail.jsp
- src/main/webapp/WEB-INF/views/board/boardList.jsp
- src/main/webapp/WEB-INF/views/faq/faqDetail.jsp
- src/main/webapp/WEB-INF/views/faq/faqEdit.jsp
- src/main/webapp/WEB-INF/views/faq/faqList.jsp
- src/main/webapp/WEB-INF/views/faq/writeFaq.jsp
- src/main/webapp/WEB-INF/views/includes/footer.jsp
- src/main/webapp/WEB-INF/views/includes/header.jsp
- 댓글 리스트
- 댓글 수정, 삭제, 작성
- 댓글 페이징
- 댓글 버튼 구현 (기본값은 안보이다가, 수정 버튼 누르면 나오게, 취소 버튼 누르면 다시 사라지도록)
- 삭제 버튼 클릭 시 '삭제하시겠습니까' Alert 창 추가
- 댓글 삭제 또는 수정 시 로그인 한 id 값과 작성한 id 값이 동일하지 않으면 수정, 삭제 버튼이 보이지 않도록 구현. 단, admin의 경우는 모두 보임
> 최종 변경 : HELP(고객센터) 댓글 구현

- src/main/webapp/WEB-INF/views/includes/footer.jsp
- src/main/webapp/WEB-INF/views/includes/header.jsp
> footer, header 링크수정

- src/main/resources/org/team/mapper/FaqBoardMapper.xml
> FaqBoardMapper.xml 오타 수정

- src/main/webapp/WEB-INF/views/board/boardDetail.jsp
Notice에서 일반회원은 수정 삭제 불가능 해야하는데 안되어 있어서 수정
> Notice에서 일반회원은 수정 삭제 불가능 해야하는데 안되어 있어서 수정
